# Generated by Django 3.1.6 on 2021-02-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=512, verbose_name='name')),
                ('item_price', models.FloatField(verbose_name='price')),
            ],
        ),
    ]
